# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ ];

  ### Bluetooth
  hardware.bluetooth.enable = lib.mkForce true;

  ### Arch
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  ### Root/home mount point located to ../filesystem/btrfs

  ### Specific mountpoint

  ### host marker
  marker = {
    hostProfile = "desktop";
    archProfile = "x86-64-v1";
  };
}
