# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos-root";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/nixos-home";
      fsType = "ext4";
    };
    
  fileSystems."/mnt/DATA" =
    { device = "/dev/disk/by-label/DATA";
      fsType = "btrfs";
      options = [ "subvol=@data" "compress=zstd:10" "nofail" "noatime" "x-gvfs-show" "nodev" "nosuid" ];
    };

  fileSystems."/mnt/Games" =
    { device = "/dev/disk/by-label/DATA";
      fsType = "btrfs";
      options = [ "subvol=@games" "compress=zstd:10" "nofail" "noatime" "nodev" "nosuid" ];
    };


  fileSystems."/mnt/Backup" =
    { device = "/dev/disk/by-label/DATA";
      fsType = "btrfs";
      options = [ "subvol=@backup" "compress=zstd:10" "nofail" "noatime" "nodev" "nosuid" ];
    };
 
 #swapDevices =
 #  [ { device = "/dev/disk/by-label/nixos-swap"; }
 #  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
