#! /usr/bin/env bash

### Use "." as a relative path 
TARGET_DIR="."

### Use realpath to have relative path to create symlink
RELATIVE_PATH=$(realpath --relative-to="$HOME" "$TARGET_DIR")

ln -sv "$RELATIVE_PATH" "$HOME/$(basename $TARGET_DIR)"

echo "Symlink created: $HOME/$(basename $TARGET_DIR) -> $RELATIVE_PATH"

