# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, ... }:

{
 fileSystems."/mnt/NAS" = { 
   ### Use hostname instead of ip
   device = "debian-pve-omv:/hdd-data";
   fsType = "nfs";
   options = [ "nofail" "nfsvers=4.2" "x-gvfs-show" "x-systemd.idle-timeout=600" ];
 };
 boot.supportedFilesystems = [ "nfs" ];
}
