# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
 fileSystems."/mnt/NAS" = { 
   device = "192.168.1.5:/hdd-data";
   fsType = "nfs";
   options = [ "nofail" "noauto" "nfsvers=4.2" "x-systemd.idle-timeout=600" ];
 };
 boot.supportedFilesystems = [ "nfs" ];
}
