# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "sd_mod"
    "sr_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ ];

  ### Bluetooth
  hardware.bluetooth.enable = lib.mkForce true;

  ### Arch
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  ### Root/home mount point located to ../filesystem/btrfs
  ### Specific mount point
  fileSystems."/mnt/DATA" = {
    label = "DATA";
    fsType = "btrfs";
    options = [
      "subvol=@data"
      "compress=zstd:5"
      "nofail"
      "noatime"
      "x-gvfs-show"
      "nodev"
      "nosuid"
    ];
  };

  fileSystems."/mnt/Games" = {
    label = "DATA";
    fsType = "btrfs";
    options = [
      "subvol=@games"
      "compress=zstd:5"
      "nofail"
      "noatime"
      "nodev"
      "nosuid"
    ];
  };

  #fileSystems."/mnt/Backup" = {
  #  label = "DATA";
  #  fsType = "btrfs";
  #  options = [
  #    "subvol=@backup"
  #    "compress=zstd:5"
  #    "nofail"
  #    "noatime"
  #    "nodev"
  #    "nosuid"
  #  ];
  #};

  ### host marker
  marker = {
    hostProfile = "desktop";
    archProfile = "x86-64-v3";
    debug.verboseOsRelease = true; # Append git branch name to bootloader entry label
  };
}
