# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
 boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
 boot.initrd.kernelModules = [ ];
 boot.kernelModules = [ "kvm-intel" ];
 boot.extraModulePackages = [ ];
  
 ### Root/home mount point located to ../filesystem/btrfs
  
 ### Specific mount point
 fileSystems."/mnt/DATA" = { 
  label = "DATA";
  fsType = "btrfs";
  options = [ "subvol=@data" "compress=zstd:5" "nofail" "noatime" "x-gvfs-show" "nodev" "nosuid" ];
 };

 fileSystems."/mnt/Games" = { 
   label = "DATA";
   fsType = "btrfs";
   options = [ "subvol=@games" "compress=zstd:5" "nofail" "noatime" "nodev" "nosuid" ];
 };

 fileSystems."/mnt/Backup" = {
   label = "DATA";
   fsType = "btrfs";
   options = [ "subvol=@backup" "compress=zstd:5" "nofail" "noatime" "nodev" "nosuid" ];
 };
  
 swapDevices = [ ];
}
